name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --no-build -c Release -o ./publish

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Live-Music'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: ./publish