name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Back_end/Back_end.csproj

    - name: Clean
      run: dotnet clean Back_end/Back_end.csproj

    - name: Build
      run: dotnet build Back_end/Back_end.csproj --no-restore

    - name: Test
      run: dotnet test Back_end/Back_end.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish Back_end/Back_end.csproj -c Release -o ./publish
